site_name: Watchtower
site_url: https://containrrr.dev/watchtower/
repo_url: https://github.com/containrrr/watchtower/
edit_uri: edit/main/docs/
theme:
  name: 'material'
  palette:
    scheme: containrrr
  logo: images/logo-450px.png
  favicon: images/favicon.ico
extra_css:
  - stylesheets/theme.css
markdown_extensions:
    - toc:
        permalink: True
        separator: "_"
    - admonition
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.magiclink:
        repo_url_shortener: True
        provider: github
        user: containrrr
        repo: watchtower
    - pymdownx.saneheaders
    - pymdownx.tabbed
nav:
   - 'Home': 'index.md'
   - 'Introduction': 'introduction.md'
   - 'Usage overview': 'usage-overview.md'
   - 'Arguments': 'arguments.md'
   - 'Notifications': 'notifications.md'
   - 'Container selection': 'container-selection.md'
   - 'Private registries': 'private-registries.md'
   - 'Linked containers': 'linked-containers.md'
   - 'Remote hosts': 'remote-hosts.md'
   - 'Secure connections': 'secure-connections.md'
   - 'Stop signals': 'stop-signals.md'
   - 'Lifecycle hooks': 'lifecycle-hooks.md'
   - 'Running multiple instances': 'running-multiple-instances.md'
   - 'Metrics': 'metrics.md'
plugins:
    - search
