blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/nicholas-fedor/watchtower/discussions
    about: Ask questions and discuss with other community members
