name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >
          Hi there! ğŸ‘‹ğŸ¼
          As you're new to this repo, we'd like to suggest that you read our [code of conduct](https://github.com/containrrr/watchtower/blob/master/CODE_OF_CONDUCT.md)
          as well as our [contribution guidelines](https://github.com/containrrr/watchtower/blob/master/CONTRIBUTING.md).
          \n
          Thanks a bunch for opening your first issue! ğŸ™
        pr-message: >
          Congratulations on opening your first pull request! ğŸ¥³\n\n
          To make sure that your pull request is handled as fast as possible, we recommend that you make sure that you make sure that you've done the following\:\n
          [ ] Documentation has been updated
          [ ] Tests have been added to all appropriate places
          [ ] Changes adhere to our [contribution guidelines](https://github.com/containrrr/watchtower/blob/master/CONTRIBUTING.md)

          Thanks! ğŸ™ğŸ¼
